pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "white cat on the grass"

train_data:
  video_path: "dataset2/white cat on the grass.mp4"
  prompt: "a white cat walking on the grass from top left to top right and then down"
  n_sample_frames: 20
  width: 256
  height: 256
  sample_start_idx: 0
  sample_frame_rate: 1

validation_data:
  prompts:
    - "a yellow duck walking on the grass from top left to top right and then down
    - "a black dog walking on the grass from top left to top right and then down"
  video_length: 20
  width: 256
  height: 256
  num_inference_steps: 100
  guidance_scale: 15
  use_inv_latent: True
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 500
checkpointing_steps: 1000
validation_steps: 50
trainable_modules:
  - "attn1.to_q"
  - "attn2.to_q"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True